### ISSUE TITLE
Admin Commands Logging in Discord Channel

### ISSUE THREAD

**Issue by PlayerWan234** [kara-b/discordfabriclink#2]
Hello,

Been using your mod for awhile but since updating to the 1.16.4 version it now displays all commands in the discord channel. Is there anyway of deactivating this?

Copy of Config with removed channel and token.

{ 
	// Bot token
	"discordBotToken": "",
	// Chatting channel ID
	"chatChannelId": "",
	// The message keys that will be sent to the public chat
	"publicKeys": [ 
		"death",
		"multiplayer",
		"chat.type.text",
		"chat.type.advancement",
		"chat.type.announcement"
	],
	// Log the keys
	"logKeys": false,
	// Webhook name
	"webhookName": "Discord Fabric Link",
	// The format to use in the Minecraft chat
	"minecraftChatFormat": "<%s> %s",
	// UUID face API
	"uuidFaceApi": "https://crafatar.com/avatars/%s?overlay&size=128"
}

**Comment by kara-b** [comment]
This has been fixed in 1.0.5 (commit 8701e0c034310e40874b24bf63a1e8cf9f1a7eb0)
